use feature ':5.10';
use strict;
use warnings;

my @reverse_me = split(//, 'not_a_palindrome');
my @sort_me = '[8, 1, 9, 8, 5, 9, 6, 5, 8, 1]';
# generated by numpy, guaranteed to be radonm

sub reverse_arr
{
    my $arg = shift @_;
    my @list = @{ $arg };
    my @out = ();

    for (my $i = 0; $i < scalar @list; $i++)
    {
        $out[scalar @list - $i - 1] = $list[$i];
    }
    return @out;
}

sub reverse_clever
{
    my $arg = shift @_;
    my @list = @{ $arg };
    my @out = ();

    map({ unshift(@out, $_) } @list);

    return @out;
}

# too lazy to sort

say reverse_arr(\@reverse_me);
say reverse_clever(\@reverse_me);
